language: node_js
node_js:
  - "0.12"
sudo: false
before_install: npm install -g gulp
before_install: npm install -g bower
#install: npm install
install: bower install
before_script: gulp build
notifications:
  webhooks:
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
